### ISSUE TITLE
Jenkins raises exceptions while testing pull requests

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/jenkins#6]
It happened to me twice today. Jenkins failed to build a pull request from github. It gave a big exception.
See the log:

```
GitHub pull request #270 of commit 060f336dd7c8b2e72e900f974c4d202a22737560, no merge conflicts.
Setting status of 060f336dd7c8b2e72e900f974c4d202a22737560 to PENDING with url https://jenkins.open-scap.org/job/openscap-pull-requests/283/ and message: 'Build started sha1 is merged.'
[EnvInject] - Loading node environment variables.
Building remotely on el6 (node-el6 rhel6) in workspace /home/jenkins/workspace/openscap-pull-requests
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git://github.com/OpenSCAP/openscap.git # timeout=10
Fetching upstream changes from git://github.com/OpenSCAP/openscap.git
 > git --version # timeout=10
 > git fetch --tags --progress git://github.com/OpenSCAP/openscap.git +refs/pull/*:refs/remotes/origin/pr/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from git://github.com/OpenSCAP/openscap.git
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
    at hudson.scm.SCM.checkout(SCM.java:485)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress git://github.com/OpenSCAP/openscap.git +refs/pull/*:refs/remotes/origin/pr/*" returned status code 128:
stdout: 
stderr: fatal: Unable to look up github.com (port 9418) (Temporary failure in name resolution)

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1640)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1388)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:62)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:313)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
    at hudson.remoting.UserRequest.perform(UserRequest.java:120)
    at hudson.remoting.UserRequest.perform(UserRequest.java:48)
    at hudson.remoting.Request$2.run(Request.java:326)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at ......remote call to el6(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
    at hudson.remoting.Channel.call(Channel.java:781)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
    at sun.reflect.GeneratedMethodAccessor217.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
    at com.sun.proxy.$Proxy51.execute(Unknown Source)
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:761)
    ... 11 more
ERROR: null
An attempt to send an e-mail to empty list of recipients, ignored.
Setting commit status on GitHub for https://github.com/OpenSCAP/openscap/commit/588187a15286d75f2f4ab6154dfdcff3c52ed7d8
Setting status of 060f336dd7c8b2e72e900f974c4d202a22737560 to FAILURE with url https://jenkins.open-scap.org/job/openscap-pull-requests/283/ and message: ' No test results found.'
Finished: FAILURE
```

**Comment by iankko** [comment]
@jan-cerny 
Does trying to re-run the test manually fix the issue?

**Comment by mpreisler** [comment]
Happened to me as well. As the exception says, this is a temporary connectivity error. I am not sure what we can do to fix that, any suggestions?

**Comment by iankko** [comment]
@mpreisler 

> I am not sure what we can do to fix that, any suggestions?

Is it possible to detect how long that DNS resolution problem will take place? Asking because thinking of something like:
- if an Jenkins exception occurs, (are we able to detect this from the scheduler?),
- and the exception text contains string `Temporary failure in name resolution`,
- wait ~10 - 15 seconds (here is necessary to know how long such a DNS name resolution failure can be present), and
- try to reschedule the test automatically.

Though not sure this would be scriptable (maybe the only way is to reschedule the test manually).

@ybznek can you hint -^

**Comment by jan-cerny** [comment]
@iankko Yes, it does, when I run it again manually it works.

**Comment by jan-cerny** [comment]
@iankko But today the issue happened also when building a pull request manually.

**Comment by isimluk** [comment]
I guess having the scheduler parsing the output can be hard.

Does it make sense for the slave to re-try the `git fetch` few times before it finally fails?

**Comment by ybznek** [comment]
Strange, that it works when you run it manually. When I connect to server via ssh, a cannot resolve any hostname.

So, I have changed DNS to 8.8.8.8 and seems to be working now. Please write comment if you will have some issues after that.

**Comment by jan-cerny** [comment]
@ybznek  Today I created pull request https://github.com/OpenSCAP/openscap/pull/274 Build finished successfully. But after it raised an exception:

```
....
....
================================================
openscap-1.2.8 archives ready for distribution: 
openscap-1.2.8.tar.gz
================================================
executing script 'Collect core dumps'
[openscap-pull-requests] $ /bin/sh /tmp/build_step_template605633917079317797.sh
No core dump found
An attempt to send an e-mail to empty list of recipients, ignored.
ERROR: Build step failed with exception
java.lang.NullPointerException
    at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:127)
    at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:105)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Build step 'Set build status on GitHub commit' marked build as failure
Setting status of 758b9dffbdee94dac47b7959b5f7b8517128b3ac to FAILURE with url https://jenkins.open-scap.org/job/openscap-pull-requests/290/ and message: ' No test results found.'
Finished: FAILURE
```

**Comment by jan-cerny** [comment]
@ybznek same exception also on  https://github.com/OpenSCAP/openscap/pull/275

**Comment by jan-cerny** [comment]
@ybznek Since yesterday, Jenkins fails for all OpenSCAP pull requests.
It fails also when we try to run the tests again using `[test this please]` command.

**Comment by ybznek** [comment]
@jan-cerny it is probably the jenkins plugins bugs. I have updated plugins when I was fixing the DNS. I will investigate it on friday.

**Comment by ybznek** [comment]
This line throws an exception.
https://github.com/jenkinsci/github-plugin/blob/master/src/main/java/com/cloudbees/jenkins/GitHubCommitNotifier.java#L127

**Comment by jan-cerny** [comment]
@ybznek What solution do you suggest for this problem? It is blocking us in our work.

**Comment by jan-cerny** [comment]
According to history of that plugin, there have been some changes performed recently around that line. Is it possible to deploy current version of the plugin?  @ybznek Could you have a look at this?

**Comment by ybznek** [comment]
Today, new version of plugin was released -> updated. Seems to work now.
